pipeline {
  agent {
    // Easiest: run in a clean Python container each build
    docker { image 'python:3.12-slim' }
  }

  options {
    timestamps()
  }

  environment {
    VENV = '.venv' 
  }

  stages {

    stage('Limpieza Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout') {
      steps {
        git url: 'https://github.com/adeyosemanputra/pygoat.git', branch: 'master'
      }
    }

    stage('Instalacion Bandit') {
      steps {
        sh '''
          ls -la
          python -V
          python -m venv "../${VENV}"
          . "../${VENV}/bin/activate"
          pip install --upgrade pip
          pip install bandit
        '''
      }
    }

    stage('Bandit SAST') {
      steps {
        sh '''
          ls -la        
          . "../${VENV}/bin/activate"
          mkdir -p reports
          bandit -r . --exit-zero -f txt -o reports/bandit_report.txt
          bandit -r . --exit-zero -f html -o reports/bandit_report.html
          bandit -r . --exit-zero -f json -o reports/bandit_report.json
        '''
      }
    }

    stage('SCA - Dependency-Track') {
      steps {
          dependencyTrackPublisher(
              artifact: 'dependency-track-bom.xml',
              projectName: 'pygoat',
              projectVersion: '1.0.0',
              dependencyTrackApiKey: credentials('dependency-track-api-key'),
              dependencyTrackUrl: 'http://localhost:8081',
              synchronous: false,
              autoCreateProjects: true
          )
      }
    }

  }

  post {
    always {
      archiveArtifacts artifacts: 'reports/*', fingerprint: true
    }
  }
}
