pipeline {
  agent {
    // Easiest: run in a clean Python container each build
    docker { image 'python:3.12-slim' }
  }

  options {
    timestamps()
  }

  environment {
    VENV = '.venv' 
  }

  stages {

    stage('Limpieza Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout') {
      steps {
        git url: 'https://github.com/adeyosemanputra/pygoat.git', branch: 'master'
      }
    }

    stage('Instalacion Bandit') {
      steps {
        sh '''
          python -V
          python -m venv "../${VENV}"
          . "../${VENV}/bin/activate"
          pip install --upgrade pip
          pip install bandit
        '''
      }
    }

    stage('Bandit SAST') {
      steps {
        sh '''      
          . "../${VENV}/bin/activate"
          mkdir -p reports
          bandit -r . --exit-zero -f txt -o reports/bandit_report.txt
          bandit -r . --exit-zero -f html -o reports/bandit_report.html
          bandit -r . --exit-zero -f json -o reports/bandit_report.json
        '''
      }
    }

    stage('Preparando dependencias') {
      steps {
        sh '''      
          . "../${VENV}/bin/activate"
          pip install cyclonedx-bom
          cyclonedx-py requirements -o ../dependency-track-bom.xml 
        '''
      }      
    }

    stage('SCA - Dependency-Track') {
      steps {
          withCredentials([
            string(credentialsId: 'dependency-track-api-key', variable: 'DTRACK_API_KEY')
          ]) {
              dependencyTrackPublisher(
                  artifact: '../dependency-track-bom.xml',
                  dependencyTrackUrl: 'http://localhost:8081',
                  dependencyTrackApiKey: DTRACK_API_KEY,
                  projectName: 'pygoat',
                  projectVersion: '1.0.0',
                  autoCreateProjects: true,
                  synchronous: false
              )
          }        
      }
    }

  }

  post {
    always {
      archiveArtifacts artifacts: 'reports/*', fingerprint: true
    }
  }
}
