pipeline {

 agent {
    docker {
      image 'tenable/terrascan:1.19.9'
      args "--entrypoint='' -u 0:0"
    }
  }

  options { timestamps() }

  stages {

    // Etapa para eliminar los archivos del workspace
    stage('Limpieza Workspace') {
      steps {
        cleanWs()
      }
    }

    stage('Checkout') {
      steps {
        sh '''
          git clone https://github.com/bridgecrewio/terragoat.git
        '''
      }
    }

    stage('Terrascan') {
      steps {
        sh '''
          mkdir -p reports/terrascan
          terrascan scan -i terraform -d terragoat/terraform/aws -o junit-xml > reports/terrascan/terrascan-junit.xml || true
          terrascan scan -i terraform -d terragoat/terraform/aws -o sarif     > reports/terrascan/terrascan.sarif || true
        '''
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'reports/terrascan/*', fingerprint: true
    }
  }

}
