pipeline {
  agent {
    // Easiest: run in a clean Python container each build
    docker { image 'python:3.12-slim' }
  }

  options {
    timestamps()
  }

  environment {
    VENV = '.venv'
    // Exclusiones comunes
    BANDIT_EXCLUDE = ".venv,static,media,migrations,__pycache__,.git,.tox"
  }

  stages {

    stage('Checkout') {
      steps {
        git url: 'https://github.com/adeyosemanputra/pygoat.git', branch: 'master'
      }
    }

    stage('Instalacion Bandit') {
      steps {
        sh '''
          python -V
          python -m venv "${VENV}"
          . "${VENV}/bin/activate"
          pip install --upgrade pip
          pip install bandit
        '''
      }
    }

    stage('Bandit SAST') {
      steps {
        sh '''
          . "${VENV}/bin/activate"
          mkdir -p reports
          ls -la
          bandit -r . -x "${BANDIT_EXCLUDE}" -f json -o reports/bandit_report.json
        '''
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'reports/bandit_report.json', fingerprint: true
    }
  }
}
